CREATE TABLE IF NOT EXISTS ipv6_subnets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    prefix VARCHAR(43) NOT NULL UNIQUE,
    bvi_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (bvi_id) REFERENCES switches(id) ON DELETE CASCADE
);